version: '3'

services:
  nucypher:
    image: nucypher:latest
    container_name: nucypher
    ports:
      - "9151:9151"
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true
